# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charts.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        MainWindow.setStyleSheet("background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:1, \n"
"        stop:0 rgb(40, 40, 40), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    color: rgb(230, 230, 230);\n"
"    background-repeat: repeat;\n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxType.setGeometry(QtCore.QRect(10, 10, 331, 31))
        self.comboBoxType.setStyleSheet("padding: 1px 18px 1px 3px;  /* Text hizalamasını etkileyebilir */\n"
"min-width: 6em;\n"
"text-align: center;  /* Qt style sheet’te doğrudan çalışmayabilir */\n"
"border: 2px solid white;\n"
"color: rgb(255,255,255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"padding: 2px 12px;")
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.buttonShow = QtWidgets.QPushButton(self.centralwidget)
        self.buttonShow.setGeometry(QtCore.QRect(380, 10, 91, 31))
        self.buttonShow.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 6px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonShow.setObjectName("buttonShow")
        self.labelChart = QtWidgets.QLabel(self.centralwidget)
        self.labelChart.setGeometry(QtCore.QRect(50, 100, 900, 650))
        self.labelChart.setStyleSheet("border: 2px solid white;")
        self.labelChart.setText("")
        self.labelChart.setObjectName("labelChart")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Charts Window"))
        self.comboBoxType.setItemText(0, _translate("MainWindow", "                     Select"))
        self.buttonShow.setText(_translate("MainWindow", "show"))
