# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1400, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 900))
        MainWindow.setStyleSheet("background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:1, \n"
"        stop:0 rgb(40, 40, 40), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    color: rgb(230, 230, 230);\n"
"    background-repeat: repeat;\n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 10, 1420, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(100, 100, 100);\n"
"    border: 3px solid white;")
        self.label.setObjectName("label")
        self.buttonRetrain = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRetrain.setGeometry(QtCore.QRect(60, 130, 161, 41))
        self.buttonRetrain.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonRetrain.setObjectName("buttonRetrain")
        self.buttonSimWin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSimWin.setGeometry(QtCore.QRect(470, 130, 261, 61))
        self.buttonSimWin.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonSimWin.setObjectName("buttonSimWin")
        self.buttonChartsWin = QtWidgets.QPushButton(self.centralwidget)
        self.buttonChartsWin.setGeometry(QtCore.QRect(250, 130, 191, 61))
        self.buttonChartsWin.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonChartsWin.setObjectName("buttonChartsWin")
        self.textBrowserStatus = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserStatus.setEnabled(False)
        self.textBrowserStatus.setGeometry(QtCore.QRect(220, 270, 31, 31))
        self.textBrowserStatus.setStyleSheet("border: 2px solid #8f8f91;\n"
"border-radius: 15px;\n"
"background-color: rgb(255, 0, 0);")
        self.textBrowserStatus.setObjectName("textBrowserStatus")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(30, 260, 241, 51))
        self.textEdit.setStyleSheet("\n"
"    border: 2px solid white;\n"
"    color: rgb(255,255,255);")
        self.textEdit.setObjectName("textEdit")
        self.tableWidgetRealtime = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetRealtime.setEnabled(True)
        self.tableWidgetRealtime.setGeometry(QtCore.QRect(20, 340, 1051, 541))
        self.tableWidgetRealtime.setStyleSheet("QTableWidget {\n"
"    font-weight: bold;       /* Kalın yazı */\n"
"    font-size: 13px;         /* Yazı boyutu biraz daha büyük */\n"
"    border: 2px solid rgb(250, 250, 250);\n"
"    background-color: rgb(60, 60, 60);\n"
"    color: rgb(230, 230, 230);\n"
"    gridline-color: rgb(250, 250, 250);\n"
"    selection-background-color: rgb(60, 120, 180);\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    font-weight: bold;       /* Kalın yazı */\n"
"    font-size: 14px;         /* Yazı boyutu biraz daha büyük */\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:0 rgb(50, 50, 50),\n"
"        stop:1 rgb(40, 40, 40)\n"
"    );\n"
"    color: white;\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"      color:rgb(0, 255, 255)    ;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(50, 50, 50);\n"
"    width: 12px;\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(100, 100, 100);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(150, 150, 150);\n"
"}\n"
"")
        self.tableWidgetRealtime.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetRealtime.setObjectName("tableWidgetRealtime")
        self.tableWidgetRealtime.setColumnCount(4)
        self.tableWidgetRealtime.setRowCount(25)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(21, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(22, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(23, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(23, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(24, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetRealtime.setItem(24, 3, item)
        self.buttonStartStop = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStartStop.setGeometry(QtCore.QRect(740, 260, 101, 51))
        self.buttonStartStop.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonStartStop.setObjectName("buttonStartStop")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1100, 140, 281, 751))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 38))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 38))
        self.textEdit_2.setStyleSheet("\n"
"    border: 2px solid white;\n"
"    color: white;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        spacerItem = QtWidgets.QSpacerItem(10, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_42 = QtWidgets.QLabel(self.frame_3)
        self.label_42.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_21.addWidget(self.label_42)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.label_benign = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_benign.sizePolicy().hasHeightForWidth())
        self.label_benign.setSizePolicy(sizePolicy)
        self.label_benign.setMinimumSize(QtCore.QSize(75, 0))
        self.label_benign.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_benign.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_benign.setObjectName("label_benign")
        self.horizontalLayout_21.addWidget(self.label_benign)
        self.horizontalLayout_21.setStretch(0, 2)
        self.horizontalLayout_21.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_22.addWidget(self.label_44)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.label_doshulk = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_doshulk.sizePolicy().hasHeightForWidth())
        self.label_doshulk.setSizePolicy(sizePolicy)
        self.label_doshulk.setMinimumSize(QtCore.QSize(75, 0))
        self.label_doshulk.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_doshulk.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_doshulk.setObjectName("label_doshulk")
        self.horizontalLayout_22.addWidget(self.label_doshulk)
        self.horizontalLayout_22.setStretch(0, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_5.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_46 = QtWidgets.QLabel(self.frame_5)
        self.label_46.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_23.addWidget(self.label_46)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.label_portscan = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_portscan.sizePolicy().hasHeightForWidth())
        self.label_portscan.setSizePolicy(sizePolicy)
        self.label_portscan.setMinimumSize(QtCore.QSize(75, 0))
        self.label_portscan.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_portscan.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_portscan.setObjectName("label_portscan")
        self.horizontalLayout_23.addWidget(self.label_portscan)
        self.horizontalLayout_23.setStretch(0, 2)
        self.gridLayout_5.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_ddos = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ddos.sizePolicy().hasHeightForWidth())
        self.label_ddos.setSizePolicy(sizePolicy)
        self.label_ddos.setMinimumSize(QtCore.QSize(75, 0))
        self.label_ddos.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_ddos.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_ddos.setObjectName("label_ddos")
        self.horizontalLayout_10.addWidget(self.label_ddos)
        self.horizontalLayout_10.setStretch(0, 2)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_6.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_48 = QtWidgets.QLabel(self.frame_6)
        self.label_48.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_24.addWidget(self.label_48)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem5)
        self.label_dosgoldeneye = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dosgoldeneye.sizePolicy().hasHeightForWidth())
        self.label_dosgoldeneye.setSizePolicy(sizePolicy)
        self.label_dosgoldeneye.setMinimumSize(QtCore.QSize(75, 0))
        self.label_dosgoldeneye.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_dosgoldeneye.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_dosgoldeneye.setObjectName("label_dosgoldeneye")
        self.horizontalLayout_24.addWidget(self.label_dosgoldeneye)
        self.horizontalLayout_24.setStretch(0, 2)
        self.gridLayout_6.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_7.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_50 = QtWidgets.QLabel(self.frame_7)
        self.label_50.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_25.addWidget(self.label_50)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem6)
        self.label_ftp = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ftp.sizePolicy().hasHeightForWidth())
        self.label_ftp.setSizePolicy(sizePolicy)
        self.label_ftp.setMinimumSize(QtCore.QSize(75, 0))
        self.label_ftp.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_ftp.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_ftp.setObjectName("label_ftp")
        self.horizontalLayout_25.addWidget(self.label_ftp)
        self.horizontalLayout_25.setStretch(0, 2)
        self.gridLayout_7.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_8.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_52 = QtWidgets.QLabel(self.frame_8)
        self.label_52.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_26.addWidget(self.label_52)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem7)
        self.label_ssh = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ssh.sizePolicy().hasHeightForWidth())
        self.label_ssh.setSizePolicy(sizePolicy)
        self.label_ssh.setMinimumSize(QtCore.QSize(75, 0))
        self.label_ssh.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_ssh.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_ssh.setObjectName("label_ssh")
        self.horizontalLayout_26.addWidget(self.label_ssh)
        self.horizontalLayout_26.setStretch(0, 2)
        self.gridLayout_8.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_9.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_54 = QtWidgets.QLabel(self.frame_9)
        self.label_54.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_27.addWidget(self.label_54)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.label_dosslowloris = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dosslowloris.sizePolicy().hasHeightForWidth())
        self.label_dosslowloris.setSizePolicy(sizePolicy)
        self.label_dosslowloris.setMinimumSize(QtCore.QSize(75, 0))
        self.label_dosslowloris.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_dosslowloris.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_dosslowloris.setObjectName("label_dosslowloris")
        self.horizontalLayout_27.addWidget(self.label_dosslowloris)
        self.horizontalLayout_27.setStretch(0, 2)
        self.gridLayout_9.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_10.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_56 = QtWidgets.QLabel(self.frame_10)
        self.label_56.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_28.addWidget(self.label_56)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem9)
        self.label_dosslowhttp = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dosslowhttp.sizePolicy().hasHeightForWidth())
        self.label_dosslowhttp.setSizePolicy(sizePolicy)
        self.label_dosslowhttp.setMinimumSize(QtCore.QSize(75, 0))
        self.label_dosslowhttp.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_dosslowhttp.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_dosslowhttp.setObjectName("label_dosslowhttp")
        self.horizontalLayout_28.addWidget(self.label_dosslowhttp)
        self.horizontalLayout_28.setStretch(0, 2)
        self.gridLayout_10.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_11.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_58 = QtWidgets.QLabel(self.frame_11)
        self.label_58.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_29.addWidget(self.label_58)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem10)
        self.label_bot = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bot.sizePolicy().hasHeightForWidth())
        self.label_bot.setSizePolicy(sizePolicy)
        self.label_bot.setMinimumSize(QtCore.QSize(75, 0))
        self.label_bot.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_bot.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_bot.setObjectName("label_bot")
        self.horizontalLayout_29.addWidget(self.label_bot)
        self.horizontalLayout_29.setStretch(0, 2)
        self.gridLayout_11.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_12.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_60 = QtWidgets.QLabel(self.frame_12)
        self.label_60.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_30.addWidget(self.label_60)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem11)
        self.label_infiltration = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infiltration.sizePolicy().hasHeightForWidth())
        self.label_infiltration.setSizePolicy(sizePolicy)
        self.label_infiltration.setMinimumSize(QtCore.QSize(75, 0))
        self.label_infiltration.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_infiltration.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_infiltration.setObjectName("label_infiltration")
        self.horizontalLayout_30.addWidget(self.label_infiltration)
        self.horizontalLayout_30.setStretch(0, 2)
        self.gridLayout_12.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_13.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_62 = QtWidgets.QLabel(self.frame_13)
        self.label_62.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_31.addWidget(self.label_62)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.label_heartbleed = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_heartbleed.sizePolicy().hasHeightForWidth())
        self.label_heartbleed.setSizePolicy(sizePolicy)
        self.label_heartbleed.setMinimumSize(QtCore.QSize(75, 0))
        self.label_heartbleed.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_heartbleed.setStyleSheet("\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    padding: 6px;")
        self.label_heartbleed.setObjectName("label_heartbleed")
        self.horizontalLayout_31.addWidget(self.label_heartbleed)
        self.horizontalLayout_31.setStretch(0, 2)
        self.gridLayout_13.addLayout(self.horizontalLayout_31, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_13)
        self.checkBoxHisFlow = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxHisFlow.setEnabled(True)
        self.checkBoxHisFlow.setGeometry(QtCore.QRect(570, 270, 141, 31))
        self.checkBoxHisFlow.setStyleSheet("QCheckBox {\n"
"    color: rgb(230, 230, 230);\n"
"    spacing: 6px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"    padding: 6px 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid rgb(180, 180, 180);\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(220, 220, 220);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"")
        self.checkBoxHisFlow.setObjectName("checkBoxHisFlow")
        self.buttonClearAll = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClearAll.setGeometry(QtCore.QRect(980, 290, 91, 31))
        self.buttonClearAll.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 6px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonClearAll.setObjectName("buttonClearAll")
        self.comboBoxNetwork = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxNetwork.setGeometry(QtCore.QRect(290, 270, 261, 31))
        self.comboBoxNetwork.setStyleSheet("border: 2px solid white;\n"
"color: rgb(255,255,255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"")
        self.comboBoxNetwork.setObjectName("comboBoxNetwork")
        self.comboBoxNetwork.addItem("")
        self.textEdit.raise_()
        self.label.raise_()
        self.buttonRetrain.raise_()
        self.buttonSimWin.raise_()
        self.buttonChartsWin.raise_()
        self.textBrowserStatus.raise_()
        self.tableWidgetRealtime.raise_()
        self.layoutWidget.raise_()
        self.buttonStartStop.raise_()
        self.checkBoxHisFlow.raise_()
        self.buttonClearAll.raise_()
        self.comboBoxNetwork.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Intrusion Detection System"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ffffff;\">Intrusion Detection System</span></p></body></html>"))
        self.buttonRetrain.setText(_translate("MainWindow", "Retrain Model"))
        self.buttonSimWin.setText(_translate("MainWindow", "Add Historical Flow\n"
"Simulation Window"))
        self.buttonChartsWin.setText(_translate("MainWindow", "Dataset and Train\n"
"Charts Window"))
        self.textBrowserStatus.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\"> Real-Time Detection <br />    Listening Status</span></p></body></html>"))
        item = self.tableWidgetRealtime.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "aga"))
        item = self.tableWidgetRealtime.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetRealtime.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "as"))
        item = self.tableWidgetRealtime.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetRealtime.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "dsada"))
        item = self.tableWidgetRealtime.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "sda"))
        __sortingEnabled = self.tableWidgetRealtime.isSortingEnabled()
        self.tableWidgetRealtime.setSortingEnabled(False)
        item = self.tableWidgetRealtime.item(0, 0)
        item.setText(_translate("MainWindow", "s"))
        item = self.tableWidgetRealtime.item(0, 1)
        item.setText(_translate("MainWindow", "sads"))
        item = self.tableWidgetRealtime.item(0, 2)
        item.setText(_translate("MainWindow", "51"))
        item = self.tableWidgetRealtime.item(0, 3)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetRealtime.item(16, 0)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetRealtime.item(16, 1)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetRealtime.item(16, 2)
        item.setText(_translate("MainWindow", "sa"))
        item = self.tableWidgetRealtime.item(16, 3)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetRealtime.item(21, 0)
        item.setText(_translate("MainWindow", "sda"))
        item = self.tableWidgetRealtime.item(21, 1)
        item.setText(_translate("MainWindow", "s"))
        item = self.tableWidgetRealtime.item(21, 2)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetRealtime.item(21, 3)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetRealtime.item(22, 0)
        item.setText(_translate("MainWindow", "3232"))
        item = self.tableWidgetRealtime.item(22, 1)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetRealtime.item(22, 2)
        item.setText(_translate("MainWindow", "dsad"))
        item = self.tableWidgetRealtime.item(22, 3)
        item.setText(_translate("MainWindow", "dsadsa"))
        item = self.tableWidgetRealtime.item(23, 0)
        item.setText(_translate("MainWindow", "dsasd"))
        item = self.tableWidgetRealtime.item(23, 1)
        item.setText(_translate("MainWindow", "das"))
        item = self.tableWidgetRealtime.item(23, 2)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetRealtime.item(23, 3)
        item.setText(_translate("MainWindow", "sa"))
        item = self.tableWidgetRealtime.item(24, 0)
        item.setText(_translate("MainWindow", "da"))
        item = self.tableWidgetRealtime.item(24, 1)
        item.setText(_translate("MainWindow", "sadd"))
        item = self.tableWidgetRealtime.item(24, 2)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetRealtime.item(24, 3)
        item.setText(_translate("MainWindow", "sadasd"))
        self.tableWidgetRealtime.setSortingEnabled(__sortingEnabled)
        self.buttonStartStop.setText(_translate("MainWindow", "Start"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Detection Counts</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "BENIGN"))
        self.label_benign.setText(_translate("MainWindow", "0"))
        self.label_44.setText(_translate("MainWindow", "DoS Hulk"))
        self.label_doshulk.setText(_translate("MainWindow", "0"))
        self.label_46.setText(_translate("MainWindow", "Port Scan"))
        self.label_portscan.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "DDoS"))
        self.label_ddos.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "DoS Golden Eye"))
        self.label_dosgoldeneye.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "FTP-Patator"))
        self.label_ftp.setText(_translate("MainWindow", "0"))
        self.label_52.setText(_translate("MainWindow", "SSH-Patator"))
        self.label_ssh.setText(_translate("MainWindow", "0"))
        self.label_54.setText(_translate("MainWindow", "DoS Slowloris"))
        self.label_dosslowloris.setText(_translate("MainWindow", "0"))
        self.label_56.setText(_translate("MainWindow", "DoS Slowhttptest"))
        self.label_dosslowhttp.setText(_translate("MainWindow", "0"))
        self.label_58.setText(_translate("MainWindow", "Bot"))
        self.label_bot.setText(_translate("MainWindow", "0"))
        self.label_60.setText(_translate("MainWindow", "Infiltration"))
        self.label_infiltration.setText(_translate("MainWindow", "0"))
        self.label_62.setText(_translate("MainWindow", "Heartbleed"))
        self.label_heartbleed.setText(_translate("MainWindow", "0"))
        self.checkBoxHisFlow.setText(_translate("MainWindow", "Historical Flow"))
        self.buttonClearAll.setText(_translate("MainWindow", "clear all"))
        self.comboBoxNetwork.setItemText(0, _translate("MainWindow", "  Select Network Interface"))
