# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 740))
        MainWindow.setMaximumSize(QtCore.QSize(850, 740))
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:1, y2:1, \n"
"        stop:0 rgb(40, 40, 40), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    color: rgb(230, 230, 230);\n"
"    background-repeat: repeat;\n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonShuffle = QtWidgets.QPushButton(self.centralwidget)
        self.buttonShuffle.setGeometry(QtCore.QRect(470, 50, 161, 41))
        self.buttonShuffle.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonShuffle.setObjectName("buttonShuffle")
        self.buttonSendAll = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSendAll.setGeometry(QtCore.QRect(660, 50, 161, 41))
        self.buttonSendAll.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonSendAll.setObjectName("buttonSendAll")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 668))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 38))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 38))
        self.textEdit_2.setStyleSheet("\n"
"    border: 2px solid white;\n"
"    color: white;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_42 = QtWidgets.QLabel(self.frame_3)
        self.label_42.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_21.addWidget(self.label_42)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.spinBox_benign = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_benign.sizePolicy().hasHeightForWidth())
        self.spinBox_benign.setSizePolicy(sizePolicy)
        self.spinBox_benign.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_benign.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_benign.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_benign.setObjectName("spinBox_benign")
        self.horizontalLayout_21.addWidget(self.spinBox_benign)
        self.horizontalLayout_21.setStretch(0, 2)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_22.addWidget(self.label_44)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.spinBox_doshulk = QtWidgets.QSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_doshulk.sizePolicy().hasHeightForWidth())
        self.spinBox_doshulk.setSizePolicy(sizePolicy)
        self.spinBox_doshulk.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_doshulk.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_doshulk.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_doshulk.setObjectName("spinBox_doshulk")
        self.horizontalLayout_22.addWidget(self.spinBox_doshulk)
        self.horizontalLayout_22.setStretch(0, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_5.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_46 = QtWidgets.QLabel(self.frame_5)
        self.label_46.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_23.addWidget(self.label_46)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem3)
        self.spinBox_portscan = QtWidgets.QSpinBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_portscan.sizePolicy().hasHeightForWidth())
        self.spinBox_portscan.setSizePolicy(sizePolicy)
        self.spinBox_portscan.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_portscan.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_portscan.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_portscan.setObjectName("spinBox_portscan")
        self.horizontalLayout_23.addWidget(self.spinBox_portscan)
        self.horizontalLayout_23.setStretch(0, 2)
        self.gridLayout_5.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.spinBox_ddos = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_ddos.sizePolicy().hasHeightForWidth())
        self.spinBox_ddos.setSizePolicy(sizePolicy)
        self.spinBox_ddos.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_ddos.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_ddos.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.spinBox_ddos.setObjectName("spinBox_ddos")
        self.horizontalLayout_10.addWidget(self.spinBox_ddos)
        self.horizontalLayout_10.setStretch(0, 2)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_6.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_48 = QtWidgets.QLabel(self.frame_6)
        self.label_48.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_24.addWidget(self.label_48)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem5)
        self.spinBox_dosgoldeneye = QtWidgets.QSpinBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_dosgoldeneye.sizePolicy().hasHeightForWidth())
        self.spinBox_dosgoldeneye.setSizePolicy(sizePolicy)
        self.spinBox_dosgoldeneye.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_dosgoldeneye.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_dosgoldeneye.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_dosgoldeneye.setObjectName("spinBox_dosgoldeneye")
        self.horizontalLayout_24.addWidget(self.spinBox_dosgoldeneye)
        self.horizontalLayout_24.setStretch(0, 2)
        self.gridLayout_6.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_7.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_50 = QtWidgets.QLabel(self.frame_7)
        self.label_50.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_25.addWidget(self.label_50)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem6)
        self.spinBox_ftp = QtWidgets.QSpinBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_ftp.sizePolicy().hasHeightForWidth())
        self.spinBox_ftp.setSizePolicy(sizePolicy)
        self.spinBox_ftp.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_ftp.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_ftp.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_ftp.setObjectName("spinBox_ftp")
        self.horizontalLayout_25.addWidget(self.spinBox_ftp)
        self.horizontalLayout_25.setStretch(0, 2)
        self.gridLayout_7.addLayout(self.horizontalLayout_25, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_8.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_52 = QtWidgets.QLabel(self.frame_8)
        self.label_52.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_26.addWidget(self.label_52)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem7)
        self.spinBox_ssh = QtWidgets.QSpinBox(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_ssh.sizePolicy().hasHeightForWidth())
        self.spinBox_ssh.setSizePolicy(sizePolicy)
        self.spinBox_ssh.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_ssh.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_ssh.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_ssh.setObjectName("spinBox_ssh")
        self.horizontalLayout_26.addWidget(self.spinBox_ssh)
        self.horizontalLayout_26.setStretch(0, 2)
        self.gridLayout_8.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_9.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_54 = QtWidgets.QLabel(self.frame_9)
        self.label_54.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_27.addWidget(self.label_54)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.spinBox_dosslowloris = QtWidgets.QSpinBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_dosslowloris.sizePolicy().hasHeightForWidth())
        self.spinBox_dosslowloris.setSizePolicy(sizePolicy)
        self.spinBox_dosslowloris.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_dosslowloris.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_dosslowloris.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_dosslowloris.setObjectName("spinBox_dosslowloris")
        self.horizontalLayout_27.addWidget(self.spinBox_dosslowloris)
        self.horizontalLayout_27.setStretch(0, 2)
        self.gridLayout_9.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_10.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_56 = QtWidgets.QLabel(self.frame_10)
        self.label_56.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_28.addWidget(self.label_56)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem9)
        self.spinBox_dosslowhttp = QtWidgets.QSpinBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_dosslowhttp.sizePolicy().hasHeightForWidth())
        self.spinBox_dosslowhttp.setSizePolicy(sizePolicy)
        self.spinBox_dosslowhttp.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_dosslowhttp.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_dosslowhttp.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_dosslowhttp.setObjectName("spinBox_dosslowhttp")
        self.horizontalLayout_28.addWidget(self.spinBox_dosslowhttp)
        self.horizontalLayout_28.setStretch(0, 2)
        self.gridLayout_10.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_11.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_58 = QtWidgets.QLabel(self.frame_11)
        self.label_58.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_29.addWidget(self.label_58)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem10)
        self.spinBox_bot = QtWidgets.QSpinBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_bot.sizePolicy().hasHeightForWidth())
        self.spinBox_bot.setSizePolicy(sizePolicy)
        self.spinBox_bot.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_bot.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_bot.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_bot.setObjectName("spinBox_bot")
        self.horizontalLayout_29.addWidget(self.spinBox_bot)
        self.horizontalLayout_29.setStretch(0, 2)
        self.gridLayout_11.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_12.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_60 = QtWidgets.QLabel(self.frame_12)
        self.label_60.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_30.addWidget(self.label_60)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem11)
        self.spinBox_infiltration = QtWidgets.QSpinBox(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_infiltration.sizePolicy().hasHeightForWidth())
        self.spinBox_infiltration.setSizePolicy(sizePolicy)
        self.spinBox_infiltration.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_infiltration.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_infiltration.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_infiltration.setObjectName("spinBox_infiltration")
        self.horizontalLayout_30.addWidget(self.spinBox_infiltration)
        self.horizontalLayout_30.setStretch(0, 2)
        self.gridLayout_12.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_13.setStyleSheet("\n"
"    border: 1px solid white;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_62 = QtWidgets.QLabel(self.frame_13)
        self.label_62.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"    font-weight: bold;\n"
"    border: 1px rgb(50, 50, 50);\n"
"    color: rgb(0,255,255);")
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_31.addWidget(self.label_62)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.spinBox_heartbleed = QtWidgets.QSpinBox(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_heartbleed.sizePolicy().hasHeightForWidth())
        self.spinBox_heartbleed.setSizePolicy(sizePolicy)
        self.spinBox_heartbleed.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_heartbleed.setMaximumSize(QtCore.QSize(75, 16777215))
        self.spinBox_heartbleed.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.spinBox_heartbleed.setObjectName("spinBox_heartbleed")
        self.horizontalLayout_31.addWidget(self.spinBox_heartbleed)
        self.horizontalLayout_31.setStretch(0, 2)
        self.gridLayout_13.addLayout(self.horizontalLayout_31, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_13)
        self.tableWidgetHisFlow = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetHisFlow.setEnabled(True)
        self.tableWidgetHisFlow.setGeometry(QtCore.QRect(320, 110, 521, 621))
        self.tableWidgetHisFlow.setStyleSheet("QTableWidget {\n"
"    font-weight: bold;       /* Kalın yazı */\n"
"    font-size: 13px;         /* Yazı boyutu biraz daha büyük */\n"
"    border: 2px solid rgb(250, 250, 250);\n"
"    background-color: rgb(60, 60, 60);\n"
"    color: rgb(230, 230, 230);\n"
"    gridline-color: rgb(250, 250, 250);\n"
"    selection-background-color: rgb(60, 120, 180);\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    font-weight: bold;       /* Kalın yazı */\n"
"    font-size: 14px;         /* Yazı boyutu biraz daha büyük */\n"
"    background-color: qlineargradient(\n"
"        spread:pad,\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:0 rgb(50, 50, 50),\n"
"        stop:1 rgb(40, 40, 40)\n"
"    );\n"
"    color: white;\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"      color:rgb(0, 255, 255)    ;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgb(50, 50, 50);\n"
"    width: 12px;\n"
"    border: 1px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(100, 100, 100);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(150, 150, 150);\n"
"}\n"
"")
        self.tableWidgetHisFlow.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetHisFlow.setObjectName("tableWidgetHisFlow")
        self.tableWidgetHisFlow.setColumnCount(4)
        self.tableWidgetHisFlow.setRowCount(25)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(21, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(21, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(22, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(22, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(23, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(23, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(24, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(24, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHisFlow.setItem(24, 3, item)
        self.buttonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAdd.setGeometry(QtCore.QRect(60, 690, 161, 41))
        self.buttonAdd.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonAdd.setObjectName("buttonAdd")
        self.buttonClearAll = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClearAll.setGeometry(QtCore.QRect(290, 70, 91, 31))
        self.buttonClearAll.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(100, 100, 100), \n"
"        stop:1 rgb(70, 70, 70)\n"
"    );\n"
"    color: rgb(0,255,255);\n"
"    border: 2px solid white;\n"
"    border-radius: 6px;\n"
"    padding: 6px 6px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 0.5px;\n"
"    font-size:16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(120, 120, 120), \n"
"        stop:1 rgb(90, 90, 90)\n"
"    );\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, \n"
"        x2:0, y2:1, \n"
"        stop:0 rgb(80, 80, 80), \n"
"        stop:1 rgb(60, 60, 60)\n"
"    );\n"
"    border: 1px solid rgb(200, 200, 200);\n"
"}\n"
"")
        self.buttonClearAll.setObjectName("buttonClearAll")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Historical Flow Simulation Window"))
        self.buttonShuffle.setText(_translate("MainWindow", "Shuffle"))
        self.buttonSendAll.setText(_translate("MainWindow", "Send All"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Select Flow Counts</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "BENIGN"))
        self.label_44.setText(_translate("MainWindow", "DoS Hulk"))
        self.label_46.setText(_translate("MainWindow", "Port Scan"))
        self.label_20.setText(_translate("MainWindow", "DDoS"))
        self.label_48.setText(_translate("MainWindow", "DoS Golden Eye"))
        self.label_50.setText(_translate("MainWindow", "FTP-Patator"))
        self.label_52.setText(_translate("MainWindow", "SSH-Patator"))
        self.label_54.setText(_translate("MainWindow", "DoS Slowloris"))
        self.label_56.setText(_translate("MainWindow", "DoS Slowhttptest"))
        self.label_58.setText(_translate("MainWindow", "Bot"))
        self.label_60.setText(_translate("MainWindow", "Infiltration"))
        self.label_62.setText(_translate("MainWindow", "Heartbleed"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "aga"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "Yeni Satır"))
        item = self.tableWidgetHisFlow.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "as"))
        item = self.tableWidgetHisFlow.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetHisFlow.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "dsada"))
        item = self.tableWidgetHisFlow.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "sda"))
        __sortingEnabled = self.tableWidgetHisFlow.isSortingEnabled()
        self.tableWidgetHisFlow.setSortingEnabled(False)
        item = self.tableWidgetHisFlow.item(0, 0)
        item.setText(_translate("MainWindow", "s"))
        item = self.tableWidgetHisFlow.item(0, 1)
        item.setText(_translate("MainWindow", "sads"))
        item = self.tableWidgetHisFlow.item(0, 2)
        item.setText(_translate("MainWindow", "51"))
        item = self.tableWidgetHisFlow.item(0, 3)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetHisFlow.item(16, 0)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetHisFlow.item(16, 1)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetHisFlow.item(16, 2)
        item.setText(_translate("MainWindow", "sa"))
        item = self.tableWidgetHisFlow.item(16, 3)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetHisFlow.item(21, 0)
        item.setText(_translate("MainWindow", "sda"))
        item = self.tableWidgetHisFlow.item(21, 1)
        item.setText(_translate("MainWindow", "s"))
        item = self.tableWidgetHisFlow.item(21, 2)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetHisFlow.item(21, 3)
        item.setText(_translate("MainWindow", "dsa"))
        item = self.tableWidgetHisFlow.item(22, 0)
        item.setText(_translate("MainWindow", "3232"))
        item = self.tableWidgetHisFlow.item(22, 1)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetHisFlow.item(22, 2)
        item.setText(_translate("MainWindow", "dsad"))
        item = self.tableWidgetHisFlow.item(22, 3)
        item.setText(_translate("MainWindow", "dsadsa"))
        item = self.tableWidgetHisFlow.item(23, 0)
        item.setText(_translate("MainWindow", "dsasd"))
        item = self.tableWidgetHisFlow.item(23, 1)
        item.setText(_translate("MainWindow", "das"))
        item = self.tableWidgetHisFlow.item(23, 2)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetHisFlow.item(23, 3)
        item.setText(_translate("MainWindow", "sa"))
        item = self.tableWidgetHisFlow.item(24, 0)
        item.setText(_translate("MainWindow", "da"))
        item = self.tableWidgetHisFlow.item(24, 1)
        item.setText(_translate("MainWindow", "sadd"))
        item = self.tableWidgetHisFlow.item(24, 2)
        item.setText(_translate("MainWindow", "sad"))
        item = self.tableWidgetHisFlow.item(24, 3)
        item.setText(_translate("MainWindow", "sadasd"))
        self.tableWidgetHisFlow.setSortingEnabled(__sortingEnabled)
        self.buttonAdd.setText(_translate("MainWindow", "Add"))
        self.buttonClearAll.setText(_translate("MainWindow", "clear all"))
